name: CI

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      # --------------------
      # Checkout
      # --------------------
      - name: Checkout repository
        uses: actions/checkout@v4


      # --------------------
      # Setup .NET
      # --------------------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          include-prerelease: true


      # --------------------
      # Restore
      # --------------------
      - name: Restore dependencies
        run: dotnet restore StockApp/StockApp.sln


      # --------------------
      # Build
      # --------------------
      - name: Build
        run: dotnet build StockApp/StockApp.sln --no-restore --configuration Release


      # --------------------
      # Test
      # --------------------
      - name: Run tests
        run: dotnet test StockApp/StockApp.sln --no-build --configuration Release


      # --------------------
      # Docker Build
      # --------------------
      - name: Build Docker image
        run: docker build -t stockapp ./StockApp